CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(1024) NOT NULL
);

CREATE TABLE access_tokens (
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE processed_files (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES user(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
)