name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false
        documentation_path: ./docs/source
        requirements_path: ./requirements.txt
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}